import './globals.css'

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by doyi',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>

        <ol>
          <li>
            <a href="/read1/">html</a>
          </li>
          <li>
            <a href="/read2/">css</a>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <a href="/ceate/">Create</a>
          </li>
          <li>
            <a href="/update1/">Update</a>
          </li>
          <li>
             <input type="button" value="delete"/>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
